[package]
name = "mandelbulb_3d_gpu"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.20"
winit = "0.29"
pollster = "0.3"
bytemuck = { version = "1.14", features = ["derive"] }
env_logger = "0.10"
log = "0.4"
glam = { version = "0.30.9", features = ["bytemuck"] }
image = "0.25.9"
